= IRI Strategy
:domain: nbnl.info
:fn-doc-iri: pass:c,q[footnote:doc-iri[For those who wonder if it is really necessary to specify both the `www` IRI type and the `doc` container type: yes it is. The `www` IRI type indicates we are requesting a web page representation of the resource. The `doc` container type tells us humans that the resource is a document. Contrast this, for example, with a web page representation of an ontology term, which would have a `www` IRI type but an `ontology` container type.]]

<<x,Resources>> and their representations are identified by IRIs, each of which must be of the following form:

.Base IRI pattern
[source,subs="attributes"]
....
https://\{kind}.{domain}/\{category}/\{namespace}[/\{version}][/\{reference}]
....

[horizontal,labelwidth=25%]
`\{kind}`::
`data` | `id` | `www` +
`\{category}`::
<<_data_products,`data-product`>> | <<_documentation,`doc`>> | <<_models,`ontology`>> | <<_models,`register`>> | <<_models,`schema`>> | <<_models,`thesaurus`>>
`\{namespace}`::
Path which encodes the namespace of the component. This can be nested as deeply as necessary, and has no formal (nor machine-readable) meaning.
`\{version}`::
Version specifier (if applicable).
`\{reference}`::
Local name of some referrent in the namespace (if applicable).

.Resource kinds
****
Traditionally, all resources were web documents of some kind or another, and the URLs locating them can serve as their identifying IRIs. More formally, those kinds of resources are called _information resources_. In this document we further distinguish two types of information resources:

* documentation information resources (indicated by the `www` subdomain)
* data information resources (indicated by the `data` subdomain)

Since the dawn of the Semantic Web, however, we want anyone to be able to say anything about anything. This includes the ability to make statements about entities or concepts in the real world. Such resources, however, are not information resources and are not on the web. To be able to state things about them, they need to have IRIs, but since they are not information resources, they are recognized as their own resource kind with a dedicated subdomain:

* real-world entities or concepts (indicated by the `id` subdomain)

[TIP]
--
If you get confused, just remember:

*Use `id` only if and only if the resource is a real-world concept or entity*.
--
****

== Categories

=== Data products

Special category which contains data products.

NOTE: This is much like a register, but data product are information resources whereas other registers are not. Therefore, to avoid confusion, and because data products are important, this special category has been introduced.

.IRI pattern for a data product
[source,subs="attributes"]
....
https://data.{domain}/data-product/\{reference}[/{version}]
....

[cols="h,2",width=70%]
|===
| Resource kind
| (`data`) data information resource

| Category
| `data-product`

| Namespace
| _n/a_

| Version +
_(optional)_
| Data product version

| Reference
| Name of the data product
|===

.Example: _Measurements_
--
.Show
[%collapsible]
====

.Generic (version-less) data product IRIs
[cols="h,3"]
|===
| Identity
.2+.^| `\https://data.{domain}/data-product/measurements`
| Data representation
| Documentation representation
| `\https://www.{domain}/data-product/measurements`
|===

.Versioned data product IRIs
[cols="h,3"]
|===
| Identity
.2+.^| `\https://data.{domain}/data-product/measurements/2.1.1`
| Data representation
| Documentation representation
| `\https://www.{domain}/data-product/measurements/2.1.1`
|===
====
--

=== Documentation

Documentation intended for reading by humans, not machines. A documentation project can consist of a mere single-page document, but also be comprised of a complex nested structure containing many pages and potentially many layers of organisation.

NOTE: Do not confuse the category _documentation_ with documentation representations as obtained through using `www` IRIs. See also: {fn-doc-iri}

.IRI pattern for a project
[source,subs="attributes"]
....
https://www.{domain}/doc/\{namespace}[/{version}]
....

.IRI pattern for a part
[source,subs="attributes"]
....
https://www.{domain}/doc/\{namespace}[/{version}]/\{reference}
....

[cols="h,2,2",width=70%]
|===
| | Project | Part

| Resource kind
2+| (`www`) documentation information resource

| Category
2+| `doc` footnote:doc-iri[]

| Namespace
2+| Namespace identifying the project

| Version +
_(optional)_
| Project version
|_n/a_

| Reference
| _n/a_
| Name (local to the project) of the part (e.g. page)
|===

.Example: _Modeling Guidelines_
--
.Show
[%collapsible]
====

.Generic (version-less) documentation IRIs
[cols="h,3"]
|===
| Identity
.2+.^| `\https://www.{domain}/doc/modeling-guidelines`
| Documentation representation

| Part identity
.2+.^| `\https://www.{domain}/doc/modeling-guidelines/cim-profiling`
| Documentation part representation
|===

.Versioned documentation IRIs
[cols="h,3"]
|===
| Identity
.2+.^| `\https://www.{domain}/doc/modeling-guidelines/1.0.0`
| Documentation representation

| Part identity
.2+.^| `\https://www.{domain}/doc/modeling-guidelines/1.0.0/cim-profiling`
| Documentation part representation
|===
====
--

=== Models

.IRI pattern for a model
[source,subs="attributes"]
....
https://data.{domain}/ontology/\{namespace}[/{version}]
....

.IRI pattern for a model element
[source,subs="attributes"]
....
https://id.{domain}/ontology/\{namespace}[/{version}]/\{reference}
....

[cols="h,2,2",width=70%]
|===
| | Model | Element

| Resource kind
a| (`data`) data information resource
a|
* (`id`) real-world concept if category is `ontology` or `thesaurus`
* (`data`) data information resource if cateogry is `schema`

| Category
2+| `ontology` \| `schema` \| `thesaurus`

| Namespace
2+| Namespace identifying the model

| Version +
_(optional)_
| Model version
|_n/a_

| Reference
| _n/a_
| Name (local to the model) of the element
|===

CAUTION: Generic (version-less) models are information resources too. They can be completely described by information such as what its name, purpose and owner is, and what versions exist of it (like one way DCAT recommends managing versions).

.Example: Data product schema
--
.Show
[%collapsible]
====
Suppose we are composing a schema for the data product _Transitietechnieken_.

.LinkML schema
[source,yaml,subs="+attributes"]
....
id: https://data.{domain}/schema/data-product/transitietechnieken <1>
version: 1.0.1 <2>
name: transitietechnieken <3>
prefixes: <4>
  nbnl: https://id.{domain}/taxonomy/energiesysteembeheer/
  cimnl: https://id.{domain}/ont/cim-nl/
classes:
  RegisteredResource:
    attributes:
      resource_type:
        slot_uri: cimnl:RegisteredResource.resourceType <5>
        range: ResourceKind
        exact_mappings:
          - nbnl:soortInstallatie <6>
....
<1> The generic IRI of the schema, i.e. not a specific version. Note that we have encoded the fact that this schema is tightly coupled to a data product in the namespace of the IRI.
<2> The version of the schema this document represents.
<3> Technical name of the schema. This has local scope, but it is good practice to keep it equal to the model name in the IRI.
<4> Prefixes for easy referring to terms from other models. Note the use of the `id` subdomain because ontology and thesauri terms are not real-world concepts.
<5> Referring to a term from an ontology.
<6> Referring to a term from a thesaurus.
====
--

=== Registers

A register is a logical container of resources which represent entities from the real-world domain. Each register contains one type of entity.

.IRI pattern for a register
[source,subs="attributes"]
....
https://data.{domain}/register/\{namespace}
....

.IRI pattern for a register entity
[source,subs="attributes"]
....
https://id.{domain}/register/\{namespace}/\{reference}
....

[cols="h,2,2",width=70%]
|===
| | Register | Entity

| Resource kind
a| (`data`) data information resource
| (`id`) real-world entity

| Category
2+| `register`

| Namespace
2+| Namespace identifying the register

| Version
2+|_n/a_

| Reference
| _n/a_
| Reference name (local to the register) of the contained entity
|===

.Example: _Substation_ register
--
.Show
[%collapsible]
====

.Register IRIs
[cols="h,3"]
|===
| Identity
.2+.^| `\https://data.{domain}/register/substation`
| Data representation

| Documentation part representation
| `\https://www.{domain}/register/substation`
|===

.Entity IRIs
[cols="h,3"]
|===
| Identity
| `\https://id.{domain}/register/substation/001231`
| Data representation
| `\https://data.{domain}/register/substation/001231`

| Documentation representation
| `\https://www.{domain}/register/substation/001231`
|===
====
--

== Resource representations

Any resource can have several representations associated with them. Each of those representations are themselves information resources, either of the data or documentation kind.

=== Real-world entities and concepts

Resources which represent real-world entities or concepts are not information resources and therefore do not have an inherent representation on the web. However, other information resources can represent them.

.Example content negotiation for a real-world entity resource
image::conneg-real-world-entities.svg[]

In a `GET` request to the `id` IRI one can make use of _content negotiation_ to clarify what type of representation is desired. The web server can then use a _303 See Other_ redirect to the URI of an information resource which provides the appropriate representation.

Typical parameters for negotiating content are language, media type or format, and version.

=== Information resources

Information resources too can have several representations, even though they are already informational in essence.

.Example content negotiation for an information resource
image::conneg-information-resources.svg[width=300]

It is especially common for data information resources such as ontologies and data products to also have documentation for humans.

NOTE: Of course, if one knows the URI of some desired representation, this URI can be used directly instead of using the redirection mechanism.

== Terms and definitions

[[def-resource]] resource:: The term _resource_ is used in a general sense for whatever might be identified by a URI. See: <<AWWW>>.

[[def-resource-description]] resource description:: A machine-readable representation of the resource, typically in some serialization of RDF.

[[def-information-resource]] information resource:: A <<def-resource>> which has the property that all of its essential characteristics can be conveyed in a message. See also: <<AWWW>>.

[bibliography]
== References

* [[[COOL-URIS]]] W3C. 2008. https://www.w3.org/TR/cooluris/[Cool URIs for the Semantic Web].
* [[[PLDN-URI]]] PLDN. https://www.pldn.nl/wiki/Boek/URI-strategie[Aanzet tot een nationale URI-Strategie voor Linked Data van de Nederlandse overheid]. Work in progress.
* [[[AWWW]]] W3C. 2004. https://www.w3.org/TR/webarch/[Architecture of the World Wide Web, Volume One].
* [[[HAWKE]]] Sandro Hawke. 2002. https://www.w3.org/2002/12/rdf-identifiers/[Disambiguating RDF Identifiers]
* [[[LOGIUS]]] Ministerie van Binnenlandse Zaken en Koninkrijksrelaties. https://www.stelselcatalogus.nl/documenten/linked_data_structuur[Linked Data structuur | Logius Stelselcatalogus]
* [[[WORKING-ONTOLOGIST]]] Dean Allemang, Jim Hendler, and Fabien Gandon. 2020. https://doi.org/10.1145/3382097[Semantic Web for the Working Ontologist: Effective Modeling for Linked Data, RDFS, and OWL (3rd. ed.)]. Association for Computing Machinery, New York, NY, USA.
* [[[LD-BP]]] W3C. 2014. https://www.w3.org/TR/ld-bp/#HTTP-URIS[Best Practices for Publishing Linked Data]. Section 5.
* [[[HALPIN]]] Harry Halpin. https://inria.hal.science/hal-01673291/document[Semantic Insecurity: Security and the Semantic Web]. PrivOn 2017 - Workshop Society,
Privacy and the Semantic Web - Policy and Technology, Oct 2017, Vienna, Austria. pp.1-10. ffhal01673291f
* [[[RFC2119]]] S. Bradner. 1997. https://www.rfc-editor.org/rfc/rfc2119[Key words for use in RFCs to Indicate Requirement Levels].
//* [[[TRIPLY]]] https://triplydb.com/how-to-model/-/stories/how-to-model-iris
* [[[DODDS-DAVIS]]] Leigh Dodds, Ian Davis. 2022. https://patterns.dataincubator.org/book/hierarchical-uris.html[Linked Data Patterns]
* [[[BOOTH]]] David Booth. 2003. https://www.w3.org/2002/11/dbooth-names/dbooth-names_clean.htm[Four Uses of a URL: Name, Concept, Web Location and Document Instance]
* [[[HTTPRANGE-14]]] Roy Fielding. 2005. https://lists.w3.org/Archives/Public/www-tag/2005Jun/0039.html[[httpRange-14\] Resolved]
* [[[TBL-GENERIC]]] Tim Berners-Lee. 1996. https://www.w3.org/DesignIssues/Generic.html[Generic Resources]
* [[[OWL2-PRIMER]]] W3C. 2012. https://www.w3.org/TR/2012/REC-owl2-primer-20121211/[OWL 2 Web Ontology Language Primer (Second Edition)]
* [[[OWL-SKOS]]] W3C. 2008. https://www.w3.org/2006/07/SWD/SKOS/skos-and-owl/master.html[Using OWL and SKOS]
