= IRI Strategy
Bart Kleijngeld <bart.kleijngeld@alliander.com>
v0.1, May 12, 2025
:description: This document lays out a standardized way for assigning IRIs to resources for the power and utilities industry in the Netherlands.
:url-repo: https://github.com/Netbeheer-Nederland/doc-iri-strategy
:domain: nbnl.info
:version: 1.0.0 (draft)

:fn-doc-iri: pass:c,q[footnote:doc-iri[For those who wonder if it is really necessary to specify both the `www` IRI type and the `documentation` category: yes it is. The `www` IRI type indicates we are requesting a web page representation of the resource. The `documentation` category tells us humans that the resource is a document. Contrast this, for example, with a web page representation of an ontology term, which would have a `www` IRI type but an `ontology` container type.]]

Author::
    mailto:bart.kleijngeld@alliander.com[Bart Kleijngeld] (Alliander)
Editors::
    mailto:ritger.teunissen@alliander.com[Ritger Teunissen] (Alliander) +
    mailto:robbert.hardin@alliander.com[Robbert Hardin] (Alliander)
Version::
    {version}
Feedback::
    https://github.com/Netbeheer-Nederland/doc-iri-strategy/issues[Issue on GitHub] (https://github.com/Netbeheer-Nederland/doc-iri-strategy[`Netbeheer-Nederland/doc-iri-strategy`])

== Abstract

This document lays out a standardized way for assigning <<RFC3987,IRIs>> (_Internationalized Resource Identifiers_) to resources for the power and utilities industry in the Netherlands.

Assigning IRIs to resources -- e.g. models, terms and real-world objects -- enables their global identification on the web which is a significant part of making data <<FAIR,FAIR>>, specifically by adhering to the <<LD,Linked Data principles>> which make possible the easy and reliable linking of data and models.

== Background
A well-defined IRI strategy is crucial to ensuring that resources on the web are uniquely and consistently identified, enabling the reliable linking, discovery, and integration of data. As the industry generates and shares large volumes of data across various stakeholders, a standardized IRI strategy is essential to achieving data interoperability, scalability, and long-term sustainability.

A core challenge within the industry is making data <<FAIR,FAIR>>: _Findable_, _accessible_, _interoperable_ and _reusable_. The use of Linked Data enables the seamless connection of diverse data sources, ensuring that data is discoverable, accessible, and machine-readable. The adoption of Linked Data within the power and utilities industry delivers the following key benefits:

* _interoperability_: ensures that data can be exchanged across different
systems, independent of technology, enhancing integration within the power and
utilities industry.

* _discoverability_: facilitates better data discovery by creating structured
URIs, making it easier for stakeholders to identify and access relevant
information.

* _machine-readability_: enables machines to interpret and process data
automatically, supporting advanced querying, analysis, and decision-making,
which improves operational efficiency.

This IRI strategy is essential to ensuring the consistent identification and
linkage of resources across the industry, advancing the broader goal of making
data FAIR. This will contribute to a more connected, efficient, and sustainable
power and utilities data ecosystem.

== Conformance
The keywords _MUST_, _MUST NOT_, _REQUIRED_, _SHALL_, _SHALL NOT_, _SHOULD_, _SHOULD NOT_, _RECOMMENDED_,  _MAY_, and _OPTIONAL_ in this document are to be interpreted as described in <<RFC2119>>.

== Scope

This document is normative for -- and only for -- minting IRIs for resources defined or maintained by Netbeheer Nederland (NBNL).

Naming conventions for the variety of categories of resources are not part of the scope of this document, and neither are versioning strategies.

[#resources]
== Resources
A <<def-resource>> can be anything we wish to state something about on the web: a certain web page, a company or the color "red". To make statements about a resource, one can refer to it by its IRI.

=== Resource kinds
Furthermore, following <<COOL-URIS,Cool URIs for the Semantic Web>> (among others), we distinguish between three kinds of resources: _documentation resources_, _data resources_ and _real-world entities or concepts_.

Each of these will be explained in the following sections.

==== Information resources
Traditionally, all resources were web documents of some kind or another, and the URLs locating them can serve as their identifying IRIs. More formally, those kinds of resources are called <<def-information-resource,_information resources_>> (colloquially referred to as _web documents_). In this document we further distinguish between two types of information resources:

* **_documentation resources_**, colloquially referred to as _web pages_ (indicated by the `www` subdomain)
* **_data resources_** (indicated by the `data` subdomain)

==== Real-world entities or concepts
Since the dawn of the Semantic Web, however, we want (anyone) to be able to say anything about anything. This includes the ability to make statements about entities or concepts in the real world. Such resources, however, are not information resources and are not on the web. To be able to state things about them, they need to have IRIs, but since they are not information resources, they are recognized as their own resource kind with a dedicated subdomain:

* **_real-world entities or concepts_** (indicated by the `id` subdomain)

[TIP]
--
If you get confused, just remember:

*Use `id` if and only if the resource refers to a real-world concept or entity*.
--
[CAUTION]
--
Ontology terms represent real-world concepts and are therefore of the `id` kind. A validation class or SHACL shape, on the other hand, are mere information resources and have no connection to the real world.
--

=== Identity and representations

The IRI that identifies a resource will sometimes be referred to as its _identity IRI_, to distinguish it explicitly from IRIs that identify representations of the resource.

We must be careful not to conflate what an IRI represents. Does it represent the thing itself, or a document describing the thing? The following example might help grasp this point.

[%collapsible]
.Example: _Cats are not descriptions of cats_
====
Suppose I want to say things about _cats_.

First, the real-world concept of a _cat_ needs a IRI so that it becomes a resource on the web I can refer to:

[cols="h,3",width=80%]
|===
| Cat
| `\https://id.example.com/animals/Cat`
|===

Then, I create a machine-readable model -- which is a _data resource_ -- in which I make statements about cats. This model gets its own IRI:

[cols="h,3",width=80%]
|===
| Model of cats
| `\https://data.example.com/models/animals`
|===

Finally, there could exist some web page with information about cats as well:

[cols="h,3",width=80%]
|===
| Web page about cats
| `\https://www.example.com/my-cats-page`
|===
====

.Takeaway point
TIP: **Things and documents providing descriptions of those things are different (kinds of) resources, each with their own IRI**.

==== Content negotiation
https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Content_negotiation[Content negotiation] (or _conneg)_ makes it possible to negotiate what representation to obtain when retrieving a resource.

This becomes a powerful mechanism when retrieving resources using their identity IRI, using 303 redirects which -- based on the provided request headers by the <<USER-AGENT,user agent>> -- to negotiate the appropriate representation which are served at different URLs. Typical parameters for negotiating content are language, media type or format, and version.

.Example content negotiation for a real-world entity resource
image::conneg-real-world-entities.svg[]

Note that information resources too can have _several_ representations, even though they are already informational in essence. No different from the previous example, here too, the identity IRI is used for retrieval:

.Example content negotiation for an information resource
image::conneg-information-resources.svg[width=300]

It is especially common for data resources such as ontologies and data products to also have documentation for humans.

NOTE: Of course, if one knows the IRI of some desired representation, this IRI can be used directly instead of using conneg.

== IRI syntax
<<def-resource,Resources>> and their representations are identified by IRIs, each of which _MUST_ be of the following syntax:

.Base IRI syntax
[source,subs="attributes"]
....
https://\{kind}.{domain}/\{category}/\{namespace}[/\{version}][/\{reference}]
....

[horizontal,labelwidth=25%]
`\{kind}`::
Resource kind. _MUST_ be one of: +
`data` | `id` | `www` +
`\{category}`::
Resource category. _SHOULD_ be one of: +
<<data-products,`data-product`>> | <<documentation,`documentation`>> | <<models,`ontology`>> | <<models,`register`>> | <<models,`schema`>> | <<models,`thesaurus`>>
`\{namespace}`::
Path which encodes the namespace of the resource. This can be nested as deeply as necessary, and has no formal (nor machine-readable) meaning.
`\{version}`::
Version specifier _(if applicable)_.
`\{reference}`::
Local name of some referent in the namespace _(if applicable)_.

== Categories

[#data-products]
=== Data products

Special category which contains data products.

NOTE: This is much like a dedicated register, but data products are <<def-information-resource,information resources>>, whereas register entities are not. Therefore, to avoid confusion, and because data products are important, this special category has been introduced.

.IRI syntax for a data product
[source,subs="attributes"]
....
https://data.{domain}/data-product/\{reference}[/\{version}]
....

[cols="h,2",width=70%]
|===
| Resource kind
| (`data`) data resource

| Category
| `data-product`

| Namespace
| _n/a_

| Version +
_(optional)_
| Data product version

| Reference
| Name of the data product
|===

.Example: _Netburen_
[%collapsible]
====

.Generic (version-less) data product IRIs
[cols="h,3",width=99%]
|===
| Identity
.2+| `\https://data.{domain}/data-product/netburen`
| Data representation
| Documentation representation
| `\https://www.{domain}/data-product/netburen`
|===

.Versioned data product IRIs
[cols="h,3",width=99%]
|===
| Identity
.2+| `\https://data.{domain}/data-product/netburen/2.1.1`
| Data representation
| Documentation representation
| `\https://www.{domain}/data-product/netburen/2.1.1`
|===
====

[#documentation]
=== Documentation

Documentation intended for reading by humans, not machines. A documentation project can consist of a mere single-page document, but also be comprised of a complex nested structure containing many pages and potentially many layers of organisation.

NOTE: Do not confuse the category _documentation_ with documentation representations as obtained through using `www` IRIs. See also: {fn-doc-iri}

.IRI syntax for a project
[source,subs="attributes"]
....
https://www.{domain}/documentation/\{namespace}[/\{version}]
....

.IRI syntax for a part
[source,subs="attributes"]
....
https://www.{domain}/documentation/\{namespace}[/\{version}]/\{reference}
....

[cols="h,2,2",width=70%]
|===
| | Project | Part

| Resource kind
2+| (`www`) documentation resource

| Category
2+| `documentation` footnote:doc-iri[]

| Namespace
2+| Namespace identifying the project

| Version +
_(optional)_
| Project version
|_n/a_

| Reference
| _n/a_
| Name (local to the project) of the part (e.g. page)
|===

.Example: _Modeling Guidelines_
[%collapsible]
====

.Generic (version-less) documentation IRIs
[cols="h,3",width=99%]
|===
| Identity
.2+| `\https://www.{domain}/documentation/modeling-guidelines`
| Documentation representation

| Part identity
.2+| `\https://www.{domain}/documentation/modeling-guidelines/cim-profiling`
| Documentation part representation
|===

.Versioned documentation IRIs
[cols="h,3",width=99%]
|===
| Identity
.2+| `\https://www.{domain}/documentation/modeling-guidelines/1.0.0`
| Documentation representation

| Part identity
.2+| `\https://www.{domain}/documentation/modeling-guidelines/1.0.0/cim-profiling`
| Documentation part representation
|===
====

[#models]
=== Models

.IRI syntax for a model
[source,subs="attributes"]
....
https://data.{domain}/\{category}/\{namespace}[/\{version}]
....

.IRI syntax for a model element
[source,subs="attributes"]
....
https://id.{domain}/\{category}/\{namespace}[/\{version}]/\{reference}
....

[cols="h,2,2",width=70%]
|===
| | Model | Element

| Resource kind
a| (`data`) data resource
a|
* (`id`) real-world concept if category is `ontology` or `thesaurus`
* (`data`) data resource if category is `schema`

| Category
2+| `ontology` \| `schema` \| `thesaurus`

| Namespace
2+| Namespace identifying the model

| Version +
_(optional)_
| Model version
|_n/a_

| Reference
| _n/a_
| Name (local to the model) of the element
|===

CAUTION: Generic (version-less) models are information resources too. They can be completely described by information such as what its name, purpose and owner is, and what versions exist of it (like one way DCAT recommends managing versions).

IMPORTANT: Never specify versions in the IRIs of model elements which represent a real-world concept, not even the model version.

.Example: Data product _Netburen_ schema
[%collapsible]
====

.Generic (version-less) data product schema IRIs
[cols="h,3",width=99%]
|===
| Identity
.2+| `\https://data.{domain}/schema/data-product/netburen`
| Data representation
| Schema documentation
| `\https://www.{domain}/schema/data-product/netburen`
|===

.Versioned data product schema IRIs
[cols="h,3",width=99%]
|===
| Identity
.2+| `\https://data.{domain}/data-product/netburen/2.1.1`
| Data representation
| Documentation representation
| `\https://www.{domain}/data-product/netburen/2.1.1`
|===

'''

Suppose we are composing a schema for the data product _Netburen_.

.LinkML schema
[source,yaml,subs="+attributes"]
....
id: https://data.{domain}/schema/data-product/netburen # <1>
version: 1.0.1 # <2>
name: netburen # <3>
prefixes: # <4>
  nbnl: https://id.{domain}/taxonomy/energiesysteembeheer/
  cimnl: https://id.{domain}/ont/cim-nl/
classes:
  MarketEvaluationPoint:
    class_uri: cim:MarketEvaluationPoint # <5>
    description: The identification of an entity where energy products are measured
      or computed.
    from_schema: https://cim.ucaiug.io/ns#TC57CIM.IEC62325.MarketManagement
    exact_mappings:
    - nbnl:aansluiting # <6>
    is_a: UsagePoint
....
<1> The generic IRI of the schema, i.e. not a specific version. Note that we have encoded the fact that this schema is tightly coupled to a data product in the namespace of the IRI.
<2> The version of the schema this document represents.
<3> Technical name of the schema. This has local scope, but it is good practice to keep it equal to the model name in the IRI.
<4> Prefixes for easy referring to terms from other models. Note the use of the `id` subdomain because ontology and thesauri terms are not real-world concepts. Also: never use versions in IRIs which represent real-world concepts.
<5> Referring to a term from an ontology.
<6> Referring to a term from a thesaurus.
====

.Example: _CIM NL_ ontology extension
[%collapsible]
====
.Generic (version-less) ontology IRIs
[cols="h,3,3",width=98%]
|===
| | Ontology | Term

| Identity
.2+| `\https://data.{domain}/ontology/cim-nl`
.2+| `\https://id.{domain}/ontology/cim-nl/EAN18Code`
| Data representation
| Documentation representation
| `\https://www.{domain}/ontology/cim-nl`
| `\https://www.{domain}/ontology/cim-nl/EAN18Code`
|===

====

=== Registers

A register is a logical container of resources which represent entities from the real-world domain. Each register contains one type of entity.

.IRI syntax for a register
[source,subs="attributes"]
....
https://data.{domain}/register/\{namespace}
....

.IRI syntax for a register entity
[source,subs="attributes"]
....
https://id.{domain}/register/\{namespace}/\{reference}
....

[cols="h,2,2",width=70%]
|===
| | Register | Entity

| Resource kind
a| (`data`) data resource
| (`id`) real-world entity

| Category
2+| `register`

| Namespace
2+| Namespace identifying the register

| Version
2+|_n/a_

| Reference
| _n/a_
| Reference name (local to the register) of the contained entity
|===

.Example: _Substation_ register
[%collapsible]
====

.Register IRIs
[cols="h,3",width=99%]
|===
| Identity
.2+| `\https://data.{domain}/register/substation`
| Data representation

| Documentation part representation
| `\https://www.{domain}/register/substation`
|===

.Entity IRIs
[cols="h,3",width=99%]
|===
| Identity
| `\https://id.{domain}/register/substation/001231`
| Data representation
| `\https://data.{domain}/register/substation/001231`

| Documentation representation
| `\https://www.{domain}/register/substation/001231`
|===
====

== Terms and definitions

[[def-resource]] resource:: The term _resource_ is used in a general sense for whatever might be identified by a URI. See: <<AWWW>>.

[[def-resource-description]] resource description:: A machine-readable representation of the resource, typically in some serialization of RDF.

[[def-information-resource]] information resource:: A <<def-resource>> which has the property that all of its essential characteristics can be conveyed in a message. See also: <<AWWW>>.

[bibliography]
== References

* [[[COOL-URIS]]] W3C. 2008. https://www.w3.org/TR/cooluris/[Cool URIs for the Semantic Web].
* [[[PLDN-URI]]] PLDN. https://www.pldn.nl/wiki/Boek/URI-strategie[Aanzet tot een nationale URI-Strategie voor Linked Data van de Nederlandse overheid]. Work in progress.
* [[[AWWW]]] W3C. 2004. https://www.w3.org/TR/webarch/[Architecture of the World Wide Web, Volume One].
* [[[HAWKE]]] Sandro Hawke. 2002. https://www.w3.org/2002/12/rdf-identifiers/[Disambiguating RDF Identifiers]
* [[[LOGIUS]]] Ministerie van Binnenlandse Zaken en Koninkrijksrelaties. https://www.stelselcatalogus.nl/documenten/linked_data_structuur[Linked Data structuur | Logius Stelselcatalogus].
* [[[WORKING-ONTOLOGIST]]] Dean Allemang, Jim Hendler, and Fabien Gandon. 2020. https://doi.org/10.1145/3382097[Semantic Web for the Working Ontologist: Effective Modeling for Linked Data, RDFS, and OWL (3rd. ed.)]. Association for Computing Machinery, New York, NY, USA.
* [[[LD-BP]]] W3C. 2014. https://www.w3.org/TR/ld-bp/#HTTP-URIS[Best Practices for Publishing Linked Data]. Section 5.
* [[[HALPIN]]] Harry Halpin. https://inria.hal.science/hal-01673291/document[Semantic Insecurity: Security and the Semantic Web]. PrivOn 2017 - Workshop Society, Privacy and the Semantic Web - Policy and Technology, Oct 2017, Vienna, Austria. pp.1-10. ffhal01673291f.
* [[[RFC2119]]] S. Bradner. 1997. https://www.rfc-editor.org/rfc/rfc2119[Key words for use in RFCs to Indicate Requirement Levels].
* [[[DODDS-DAVIS]]] Leigh Dodds, Ian Davis. 2022. https://patterns.dataincubator.org/book/hierarchical-uris.html[Linked Data Patterns].
* [[[BOOTH]]] David Booth. 2003. https://www.w3.org/2002/11/dbooth-names/dbooth-names_clean.htm[Four Uses of a URL: Name, Concept, Web Location and Document Instance].
* [[[HTTPRANGE-14]]] Roy Fielding. 2005. https://lists.w3.org/Archives/Public/www-tag/2005Jun/0039.html[[httpRange-14\] Resolved].
* [[[TBL-GENERIC]]] Tim Berners-Lee. 1996. https://www.w3.org/DesignIssues/Generic.html[Generic Resources].
* [[[OWL2-PRIMER]]] W3C. 2012. https://www.w3.org/TR/2012/REC-owl2-primer-20121211/[OWL 2 Web Ontology Language Primer (Second Edition)].
* [[[OWL-SKOS]]] W3C. 2008. https://www.w3.org/2006/07/SWD/SKOS/skos-and-owl/master.html[Using OWL and SKOS].
* [[[LD]]] W3C. 2006. https://www.w3.org/DesignIssues/LinkedData[Linked Data].
* [[[RFC3987]]] W3C. 2005. https://datatracker.ietf.org/doc/rfc3987/[Internationalized Resource Identifiers (IRIs)].
* [[[FAIR]]] GO FAIR. https://www.go-fair.org/fair-principles/[FAIR Principles].
* [[[USER-AGENT]]] W3C. 2011. https://www.w3.org/WAI/UA/work/wiki/Definition_of_User_Agent[Definition of User Agent].
