= URI Policy
Bart Kleijngeld <bart.kleijngeld@alliander.com>
v0.1, May 12, 2025
:description: This document lays out a standardized way for assigning URIs to resources for the power and utilities industry in the Netherlands.
:url-repo: https://github.com/Netbeheer-Nederland/doc-uri-policy
:domain: nbnl.info
:version: v2.0.0-rc1
:uri: https://{domain}/uri-policy

Author:: mailto:bart.kleijngeld@alliander.com[Bart Kleijngeld] (Alliander)
//Editors::
//mailto:ritger.teunissen@alliander.com[Ritger Teunissen] (Alliander) +
//mailto:robbert.hardin@alliander.com[Robbert Hardin] (Alliander)
Version:: {version}
Feedback:: https://github.com/Netbeheer-Nederland/doc-uri-policy/issues[Issue on GitHub] (https://github.com/Netbeheer-Nederland/doc-uri-policy[`Netbeheer-Nederland/doc-uri-policy`])

////
== Abstract

This document lays out a standardized way for assigning <<RFC3986,URIs>> (_Uniform Resource Identifiers_) to resources for the power and utilities industry in the Netherlands.

Assigning URIs to resources -- e.g. models, terms and real-world objects -- enables their global identification on the web which is a significant part of making data <<FAIR,FAIR>>, specifically by adhering to the <<LD,Linked Data principles>> which make possible the easy and reliable linking of data and models.

== Concepts

[#resources]
=== Resources and identification

To make statements about something on the Web it must be assigned a URI which identifies it. Anything that can be identified on the web by a URI is called a _resource_.

Virtually anything can be a resource, e.g. your personal website, a data model, the office building you work in and even the concept of love.
////

////
.Philosophical note on identity
****
According to the Meaning of Meaning model, symbols -- such as URIs -- are fundamentally limited to symbolizing senses or conceptualizations of things in reality, and can never symbolize those things themselves. Focusing on models, this means the URI `\https://nbnl.info/esb/aansluiting` does refer symbolize the concept _aansluiting_, but rather its conceptualization as defined in the model `esb`.

Interestingly, the Web and the REST architectural view have taken a more pragmatic approach by allowing _late-binding_. This means URIs can symbolize something prior to it having a representation that provides its meaning. This is at odds with the Meaning of Meaning model.

In this policy we favor pragmatism over purity, and since the policy regards identification on the Web, it makes sense to adhere to its principles.
    
////

////
===== URL, URN, URI and IRI

Specializations of URIs exist, such as URLs and URNs, which have narrower definitions.

IRIs are a superset of URIs which set out to extend the character set allowed to be used for internationalization purposes, but because the standard is still in the proposal stage we stick with URIs.

==== Representations

Resources can have representations, which can be thought of as documents which represent the resource on the Web. If available, representations can be retrieve by dereferencing the URI. In the case a resource has multiple representations, content-negotiation can be used negotiate which one to retrieve.

==== Information resources

==== Real-world things

==== Content-negotiation



=== URL, URN, URI and IRI
URLs are the subset of URIs which do not only identify a resource, but also locate resource representations.

For identification of resources on the web, URIs SHOULD b

[quote]
--
The term "Uniform Resource Locator" (URL) refers to the subset of URIs that, in addition to identifying a resource, provide a means of locating the resource by describing its primary access mechanism (e.g., its network "location").  The term "Uniform Resource Name" (URN) has been used historically to refer to both URIs under the "urn" scheme [RFC2141], which are required to remain globally unique and persistent even when the resource ceases to exist or becomes unavailable, and to any other URI with the properties of a name.

An individual scheme does not have to be classified as being just one of "name" or "locator".  Instances of URIs from any given scheme may have the characteristics of names or locators or both, often depending on the persistence and care in the assignment of identifiers by the naming authority, rather than on any quality of the scheme.  Future specifications and related documentation should use the general term "URI" rather than the more restrictive terms "URL" and "URN" [RFC3305].
--

URLs are superseded by URIs, although the use of the term remains popular when referring specifically to web addresses and not to resources in a more semantic sense.

URIs supsersede URIs, allowing for a much larger character set to be used for internationalization purposes. However, whereas URIs are formalized in an RFC _Internet standard_, URIs are currently merely a _Proposed standard_, Since the extended character does not solve
////


== Rationale
Managing data can be challenging, especially when data is exchanged across organizational boundaries or integrated from multiple sources. The <<FAIR,FAIR>> (_Findable, Accessible, Interoperable, Reusable_) principles provide guidance to address these challenges. By emphasizing machine-actionability and the extended use of metadata, they help ensure that data can be properly managed, governed, made interopable, and reused.

To implement FAIR data management, <<dfn-the-web,the Web>> is a fitting foundation, particularly when making use of <<dfn-semamtic-web,Semantic Web>> technologies, <<dfn-linked-data,Linked Data>> principles and other W3C standards. This requires the ability to identify (meta)data on the Web, and for that <<dfn-uri,URIs>> (_Uniform Resource Identifiers_) are necessary: they are identifiers of <<dfn-resource,resources>> on the Web.

.FAIR principles
****
This document helps satisfy the following FAIR principles ^<<FAIR>>^:

// .FAIR principles
* _F1. (Meta)data are assigned a globally unique and persistent identifier_
* _A1. (Meta)data are retrievable by their identifier using a standardised communications protocol_
* _A3. Metadata are accessible, even when the data are no longer available_
****

== Scope
This document provides the necessary background information and guidance to help one to:

* Design stable URIs for resource identification on the Web
* Implement representation retrieval upon interaction with URIs

Actual design and implementation details are left to the reader. footnote:[This is scoped as such on purpose, because different (kinds of) resources can benefit from vastly different URI designs, and trying to design a general base URI template upfront will end up being either too rigid to fit all cases, or impenetrably abstract and therefore hard to use and potentially useless.]

== Foundational concepts

<<dfn-uri,URIs>> (_Uniform Resource Identifiers_) are identifiers of <<dfn-resource,resources>> on <<dfn-the-web,the Web>>, and resources are all things which have a URI assigned to them^<<AWWW>>^.

////
.URIs, URLs, URNs and IRIs
****
* **URIs (Uniform Resource Identifiers)** are generic resource identifiers.
** **URLs (Uniform Resource Locators)** are URIs that specify how to locate and access a resource, typically through a network protocol such as HTTP.
** **URNs (Uniform Resource Names)** are URIs using the `urn:` scheme, intended as persistent, opaque identifiers that are not required to be dereferenceable.
* **IRIs (Internationalized Resource Identifiers)** are a superset of URIs that allow the full range of Unicode characters, making them easier to use in multilingual and human-facing contexts.

This policy favors IRIs over URIs because they are more human-friendly, while still interoperable with Web standards (IRIs can always be automatically mapped to URIs by systems).

****
////

Some resources are purely informational, meaning their essence can be encoded into a stream of bytes which represents the resource on the Web. These resources are called <<dfn-information-resource,information resources>>^<<AWWW>>^ or -- more colloquially -- <<dfn-web-document,web documents>>footnote:[Technically, web documents are information resources which have a representation. The nuance here is that information resources _can_ be represented on the Web, and do not need to have representations at any given time. This is only an academic concern, however, and in practice information resources and web documents are used interchangeably throughout this document].

Resources which are not information resources are often referred to as <<dfn-real-world-thing,real-world things>>. These include physical, tangible objects, but also abstract concepts. These resources cannot have representations on the Web, since their essence can never be fully captured by information.footnote:[Philosophers of language have studied this phenomenon in depth, but further detail is out of scope for this document. Further reading of interest may include xref:https://en.wikipedia.org/wiki/Family_resemblance[Ludwig Wittgenstein's idea of family resemblances.]]

.Representations vs descriptions
[CAUTION]
--
Although real-world things cannot be _represented_ on the Web, there can of course be web documents which _describe_ the real-world thing (by referring to it by its URI).footnote:[From a URI assignment point of view, there would be a URI identifying the real-world thing (resource), and distinct URIs for each web document which provides a description of the resource in question.]
--

////
Every resource falls in either of the following two categories:^<<COOL-URIS>>^footnote:[The more formal <<AWWW>> bipartitions resources into those which are _information resources_ and those which are not. This parititon closely resembles the one made between _web documents_ and _real-world things_ made in <<COOL-URIS>>, but is not quite equivalent because web documents are a subset of information resources which have a representation. In practice this nuance is hardly ever relevant, so in this document the more accessible jargon from <<COOL-URIS>> is used.]

* *web documents*: documents of which content is available for retrieval on the Web, e.g. web pages, JSON documents and images.
* *real-world things*: real-world objects or abstract concepts, e.g. the building you live in and the concept of "love".

There are resources which can be represented on the Web, meaning it is possible to encode the essence of the resource into a sequence of bytes.
////






////
Resources can have <<dfn-representation,representations>>, meaning one can retrieve information from the Web which represent the resource.  _ There are also resources which can merely be identified, but do not or even cannot have representations.
////




////
// .From URL to URI
// ****
Traditionally, the Web consisted of information resources only, namely web pages and assets such as images which were addressable using <<dfn-url,URLs>> (_Uniform Resource Locators_).

On the modern Web, however, URLs have been generalized to <<dfn-uri,URIs>> (_Uniform Resource Identifiers_) whose function is merely that of identification, not necessarily locating. URIs thereby made it possible to identify things other than web documents, allowing information to refer to real-world subjects unambiguously and consistently.

The <<dfn-semantic-web, Semantic Web>> built on this, extending the World Wide Web which consists largely of unstructured data intended for humans with a counterpart revolving around semantically annotated structured data intended for machines.
// ****
////

A resources can have multiple representations, in which case <<dfn-content-negotiation,content negotiation>> can be used to specify what representation is preferred. Representations may differ in the <<dfn-media-format,media format>>, language or character set,

The HTTP application protocol also supports redirection from one URI to another. Using `303 See Other` enables redirecting of a URI identifying a real-world thing to a web document providing a description of it. Furthermore, information resources may be redirected using `307 Temporary Redirect` to defer to another location where the representation is to be served from.




== URI design

Thou shalt not.

* Stability
* Opacity

== Representation retrieval


=== Real-world things

* have no representations on the Web
* hash vs slash (303)
** 303 redirectsfootnote:[Note that `303 (See Other)` redirects should not be used for any other purpose. ^<<httpRange-14>>^.] to defer representation to an information resource
*** Generic document pattern (COOL-URIs 4.2) to redirect terms to the authoritative models which provide their normative definitions
*** URI is replaced by the client to the document one so bookmarking etc. is easier

.Hash vs slash
****
Another common pattern to deal with retrieving descriptions of real-world things is to use the hash convention.

In this convention, terms are identified by their defining models URI, followed by a hash symbol and then the term name. Due to how the HTTP protocol is implemented, web servers will truncate the fragment and therefore by default provide the agent with a representation of the entire model. This is welcome behavior in many cases, but there are some issues.

First off, it is ambiguous what the term URI means when retrieving a HTML representation. Fragments are often used as denotations of anchors in the document, which is semantically different of course from the real-world entity.

Furthermore, in the case separate web pages exist for a single term, the aforementioned truncation of the fragment cause web servers to be unable to distinguish between the model and the term for its description.

Slashes therefore provide more server-sided control, more freedom in how URIs are designed, and avoid ambiguity. In fact, using slashes and 303 redirects explicitly states: this resource is not an information resource.
****

=== Information resources
* 307 redirects from stable interface URI to implementation specific URI
** URI is not replaced by the client so that original URI is treated as the canonical




////
Question!

* What are URIs and what do I need them for?
** Identifiers for Web resources
** Necessary if you want to identify to something on the Web, such as hosting a software application or making statements about something in the real world
* What things should or need to be assigned URIs, and when are they not necessary?
** Anything that needs to be addressable or referable on the Web
** URIs can form an interface for a Web application
*** Internal URIs should be exposed as least as possible, and hypermedia-driven discovery should be favored
* What constitutes a good URI? Any best practices for creating them?
** Use HTTPS
** Opacity and stability are very important
** Simple and without much information encoded in it (meaningful hints are fine sparingly, but make sure the info is non-volatile as possible such as rigid types)
* How can URIs be interacted with to retrieve representations?
** Rely on standard Web and HTTP technology such as verbs, requests/response and redirects
** Non-information vs information resources and hash vs slash
** Content-negotiation
////

=== Content-negotation

* In the case where multiple representations exist of a resource, content-negotiation must be used to discern between what representation is returned.

'''

== Appendix: URI reference

// #NOTE#: We now have two worlds to keep in sync. The tables here and in the definition type pages. I don't like that. I would much rather refer to hose from here instead of duplicating the tables here.

With the preceding background and guidance in mind, Team Semantiek has designed URI templates for all the xref:doc-team-semantiek:projects:index.adoc[types of definitions] they are responsible for.

=== Data product application profile

TIP: For more information, see: xref:doc-team-semantiek:projects:application-profile/index.adoc[].

.URI templates for data product application profile
include::doc-team-semantiek:projects:partial$application-profile/uri-templates-data-product.adoc[]

.Example URIs: Capaciteitskaart
[%collapsible]
====
include::doc-team-semantiek:projects:partial$application-profile/example-uris-capaciteitskaart.adoc[]
====

=== Controlled vocabulary

TIP: For more information, see: xref:doc-team-semantiek:projects:controlled-vocabulary/index.adoc[].

.URI templates for controlled vocabulary
include::doc-team-semantiek:projects:partial$controlled-vocabulary/uri-templates.adoc[]

.Example URIs: Energiesysteembeheer
[%collapsible]
====
include::doc-team-semantiek:projects:partial$controlled-vocabulary/example-uris-energiesysteembeheer.adoc[]
====

=== Documentation

TIP: For more information, see: xref:doc-team-semantiek:projects:documentation/index.adoc[].

.URI templates for documentation
include::doc-team-semantiek:projects:partial$documentation/uri-templates.adoc[]

.Example URIs
[%collapsible]
====
include::doc-team-semantiek:projects:partial$documentation/example-uris.adoc[]
====
