= IRI Strategy
:domain: nbnl.info
:fn-doc-iri: pass:c,q[footnote:doc-iri[For those who wonder if it is really necessary to specify both the `www` IRI type and the `doc` container type: yes it is. The `www` IRI type indicates we are requesting a web page representation of the resource. The `doc` container type tells us humans that the resource is a document. Contrast this, for example, with a web page representation of an ontology term, which would have a `www` IRI type but an `ontology` container type.]]

== Introduction

#TODO#

== IRI patterns

<<x,Resources>> and their representations are identified by IRIs, each of which must be of the following form:

.Base IRI pattern
[source,subs="attributes"]
....
https://\{kind}.{domain}/\{category}/\{namespace}[/\{version}][/\{reference}]
....

[horizontal,labelwidth=25%]
`\{kind}`::
    `data` | `id` | `www` +
`\{category}`::
    <<_data_product,`data-product`>> | <<_documentation,`doc`>> |<<_models,`ontology`>> | <<_models,`register`>> | <<_models,`schema`>> | <<_models,`thesaurus`>>
`\{namespace}`::
    Path which encodes the namespace of the component. This can be nested as deeply as necessary, and has no formal (nor machine-readable) meaning.
`\{version}`::
    Version specifier (if applicable).
`\{reference}`::
    Local name of some referrent in the namespace (if applicable).

.Resource kinds
****
Traditionally, all resources were web documents of some kind or another, and the URLs locating them can serve as their identifying IRIs. More formally, those kinds of resources are called _information resources_. In this document we further distinguish two types of information resources:

* documentation information resources (indicated by the `www` subdomain)
* data information resources (indicated by the `data` subdomain)

Since the dawn of the Semantic Web, however, we want anyone to be able to say anything about anything. This includes the ability to make statements about entities or concepts in the real world. Such resources, however, are not information resources and are not on the web. To be able to state things about them, they need to have IRIs, but since they are not information resources, they are recognized as their own resource kind with a dedicated subdomain:

* real-world entities or concepts (indicated by the `id` subdomain)

Note there can be information representations which represent another resource. For example,
****

////
.IRIs for each category (version-less)
====
[cols="2h,5"]
|===
|Documentation project
|`\https://www.{domain}/doc/modeling-guidelines`

|Documentation project page
|`\https://www.{domain}/doc/modeling-guidelines/iri-strategy/decisions`

|Data product
|`\https://data.{domain}/data-product/measurements`

|Ontology
|`\https://data.{domain}/ontology/core-equipment`

|Ontology term
|`\https://data.{domain}/ontology/core-equipment#Wire`

|Schema
|`\https://data.{domain}/schema/forecasting`

|Schema element
|`\https://data.{domain}/schema/forecasting#OpertionalLimit`

|Thesaurus
|`\https://data.{domain}/thesaurus/energy-system`

|Thesaurus term
|`\https://data.{domain}/thesaurus/energy-system#usage-point`

|Register
|`\https://id.{domain}/lv-measurements/`

|Register entity
|`\https://id.{domain}/lv-measurements/021`

|===
====
////

=== Registers

A register is a logical container of resources which represent entities from the real-world domain. Each register contains one type of entity.

.IRI pattern for a register
[source,subs="attributes"]
....
https://data.{domain}/register/\{namespace}
....

.IRI pattern for a register entity
[source,subs="attributes"]
....
https://id.{domain}/register/\{namespace}/\{reference}
....

[cols="h,2,2",width=70%]
|===
| | Register | Entity

| Resource kind
a| (`data`) data information resource
| (`id`) real-world entity

| Category
2+| `register`

| Namespace
2+| Namespace identifying the register

| Version
2+|_n/a_

| Reference
| _n/a_
| Reference name (local to the register) of the contained entity
|===

.Substation register
====
To keep track of all substations in the Netherlands, a register has been called into life:

.The register
[source,subs="attributes"]
....
https://data.{domain}/register/substation
....

This register contains all known substations, and nothing else.

.An individual substation
[source,subs="attributes"]
....
https://id.{domain}/register/substation/001231
....

Since a substation is a real-world entity and not an information resource, the `id` subdomain must be used.
====

=== Models

.IRI pattern for a model
[source,subs="attributes"]
....
https://data.{domain}/ontology/\{namespace}[/{version}]
....

.IRI pattern for a model element
[source,subs="attributes"]
....
https://id.{domain}/ontology/\{namespace}[/{version}]/\{reference}
....

[cols="h,2,2",width=70%]
|===
| | Model | Element

| Resource kind
a| (`data`) data information resource
| (`id`) real-world conceptfootnote:[Is this always accurate? For ontologies and thesauri: yes. But do SHACL shapes and LinkML classes, for example, also represent something from the real world?]

| Category
2+| `ontology` \| `thesaurus` \| `schema`

| Namespace
2+| Namespace identifying the model

| Version +
_(optional)_
a| Model version, following the pattern:

`X.Y.Z` +

(where `X, Y, Z` are non-negative integers)
a|_n/a_

| Reference
| _n/a_
| Name (local to the model) of the element
|===

CAUTION: Generic (version-less) models are information resources too. They can be completely described by information such as what its name, purpose and owner is, and what versions exist of it (like one way DCAT recommends managing versions).

.Data product schema
====
Suppose we are composing a schema for the data product _Transitietechnieken_.

.LinkML schema
[source,yaml,subs="+attributes"]
....
id: https://data.{domain}/schema/data-product/transitietechnieken
version: 1.0.1 <2>
name: transitietechnieken <3>
prefixes: <4>
  nbnl: https://id.{domain}/taxonomy/energiesysteembeheer/
  cimnl: https://id.{domain}/ont/cim-nl/
classes:
  RegisteredResource:
    attributes:
      resource_type:
        slot_uri: cimnl:RegisteredResource.resourceType <5>
        range: ResourceKind
        exact_mappings:
          - nbnl:soortInstallatie <6>
....
<1> The generic IRI of the schema, i.e. not a specific version. Note that we have encoded the fact that this schema is tightly coupled to a data product in the namespace of the IRI.footnote:[#TODO#: Should this be enforced and therefore documented outside a mere example?]
<2> The version of the schema this document represents.
<3> Technical name of the schema. This has local scope, but it is good practice to keep it equal to the model name in the IRI.
<4> Prefixes for easy referring to terms from other models. Note the use of the `id` subdomain because ontology and thesauri terms are not real-world concepts.
<5> Referring to a term from an ontology.
<6> Referring to a term from a thesaurus.
====

=== Documentation

Documentation intended for reading by humans, not machines. A documentation project can consist of a mere single-page document, but also be comprised of a complex nested structure containing many pages and potentially many layers of organisation.

NOTE: Do not confuse the category _documentation_ with documentation representations as obtained through using `www` IRIs. See also: {fn-doc-iri}

.IRI pattern for a project
[source,subs="attributes"]
....
https://www.{domain}/doc/\{namespace}[/{version}]
....

.IRI pattern for a part
[source,subs="attributes"]
....
https://www.{domain}/doc/\{namespace}[/{version}]/\{reference}
....

[cols="h,2,2",width=70%]
|===
| | Project | Part

| Resource kind
2+| (`www`) documentation information resource

| Category
2+| `doc` footnote:doc-iri[]

| Namespace
2+| Namespace identifying the project

| Version +
_(optional)_
a| Project version, following the pattern:

`X.Y.Z` +

(where `X, Y, Z` are non-negative integers)
a|_n/a_

| Reference
| _n/a_
| Name (local to the project) of the part (e.g. page)
|===

=== Data product

Special category which contains data products.

NOTE: This is much like a register, but data product are information resources whereas other registers are not. Therefore, to avoid confusion, and because data products are important, this special category has been introduced.

.IRI pattern for a data product
[source,subs="attributes"]
....
https://data.{domain}/data-product/\{reference}[/{version}]
....

[cols="h,2",width=70%]
|===
| Resource kind
| (`data`) data information resource

| Category
| `data-product`

| Namespace
| _n/a_

| Version +
_(optional)_
a| Data product version, following the pattern:

`X.Y.Z` +

(where `X, Y, Z` are non-negative integers)

| Reference
| Name of the data product
|===

== Resource representations

Any resource can have several representations associated with them. Each of those representations are themselves information resources, either of the data or documentation kind.

=== Real-world entities and concepts

Resources which represent real-world entities or concepts are not information resources and therefore do not have an inherent representation on the web. However, other information resources can represent them.

.Example content negotiation for a real-world entity resource
image::conneg-real-world-entities.svg[]

In a `GET` request to the `id` IRI one can make use of _content negotiation_ to clarify what type of representation is desired. The web server can then use a _303 See Other_ redirect to the URI of an information resource which provides the appropriate representation.

Typical parameters for negotiating content are language, media type or format, and version.

=== Information resources

Information resources too can have several representations, even though they are already informational in essence.

.Example content negotiation for an information resource
image::conneg-information-resources.svg[width=300]

It is especially common for data information resources such as ontologies and data products to also have documentation for humans.

'''

NOTE: Of course, if one knows the URI of some desired representation, this URI can be used directly instead of using the redirection mechanism.

////
== Versioning



== Example

.IRI Strategy
====
Let's consider the IRI for the _IRI Strategy_ document.

.Generic IRI
[source,subs="attributes"]
....
https://www.{domain}/doc/modeling-guide/iri-strategy
....

Note that it is part of the _Modeling Guide_ documentation project, which would act as its container.

To request a specific version of the _Modeling Guide_ one could use the following IRI:

.Versioned IRI
[source,subs="attributes"]
....
https://www.{domain}/doc/modeling-guide/1.1.0/iri-strategy
....

Note that it is not supported to version the _IRI Strategy_ document itself, only the project it is contained in. This is analogous to the inability to version ontology terms.

.IRI to Specific page
[source,subs="attributes"]
....
https://www.{domain}/doc/modeling-guide/iri-strategy/decisions
....

If documentation consists of multiple pages, these can be referenced simply by expanding the path as illustrated in this example.

====

== Models
.IRI pattern for models
[source,subs="attributes"]
....
https://data.{domain}/\{model-type}/\{model}[/\{version}]
....

.IRI pattern for model elements
[source,subs="attributes"]
....
https://data.{domain}/\{model-type}/\{model}[/\{version}]/\{element}
....

[cols="h,1",width=70%]
|===
| Model type
a| Any of:

* `<<x,thesaurus>>`
* `<<x,ont>>`
* `<<x,schema>>`

| Model
| Name of the model

| Version +
_(optional)_
a| Version of the model, following the pattern:

`X.Y.Z` +

(where `X, Y, Z` are non-negative integers)

| Element
| Name (local to the model) of the model element which corresponds to the resource
|===

== Resource kinds

== Versioning

//== Example

.LinkML schema of data product _Transitietechnieken_
--
[%collapsible]
====
[source,yaml,subs="+attributes"]
....
id: https://data.{domain}/schema/data-product/transitietechnieken <1>
version: 1.0.1 <2>
name: transitietechnieken <3>
prefixes: <4>
  nbnl: https://id.{domain}/taxonomy/energiesysteembeheer/
  cimnl: https://id.{domain}/ont/cim-nl/
classes:
  RegisteredResource:
    class_uri: cim:RegisteredResource
    attributes:
      resource_type:
        slot_uri: cimnl:RegisteredResource.resourceType <5>
        range: ResourceKind
        exact_mappings:
          - nbnl:soortInstallatie <6>
....
<1> The generic IRI of the schema, i.e. not a specific version.
<2> The version of the schema this document represents.
<3> Technical name of the schema. This has local scope, but it is good practice to keep it equal to the model name in the IRI.
<4> Prefixes for easy referring to terms from other models.
<5> Referring to a term from another ontology.
<6> Referring to a term from another thesaurus.
====
--
////