= IRI Strategy
:domain: nbnl.info
:fn-doc-iri: pass:c,q[footnote:doc-iri[For those who wonder if it is really necessary to specify both the `www` IRI type and the `doc` container type: yes it is. The `www` IRI type indicates we are requesting a web page representation of the resource. The `doc` container type tells us humans that the resource is a document. Contrast this, for example, with a web page representation of an ontology term, which would have a `www` IRI type but an `ontology` container type.]]

== Introduction

#TODO#

////
== IRI pattern

<<x,Resources>> and their representations are identified by IRIs, each of which must be of the following form:

.IRI pattern
[source,subs="attributes"]
....
https://\{uri-type}.{domain}/\{category}/\{path}{[/\{version}]/\{reference}
....

Where:

* The path `/\{category}/\{container}[/\{version]}/\{reference}` is the fully qualified name of the resource being identified.
* The `\{uri-type}` indicates what representation of the resource is desired.

#TODO#: Write more. Including explanation of all path components.
////

////
== Reference

[cols="1h,3,1,1"]
|===
| |Description |URI type |Category

|Register
|Register of real-world entities
|`id`
|`register`

|<<_data_product>>
|Data product definitions
|`www`
|`dprod`

|Ontology
|Ontology or conceptual model
|`data`
|`ontology`

|Schema
|Logical or technical data model
|`data`
|`schema`

|Thesaurus
|Thesaurus, taxonomy, controlled vocabulary or glossary
|`data`
|`thesaurus`

|<<_documentation_project>>
|Documentation for humans
|`www`
|`doc`

|===
////

////
.IRIs for each category (version-less)
====
[cols="2h,5"]
|===
|Documentation project
|`\https://www.{domain}/doc/modeling-guidelines`

|Documentation project page
|`\https://www.{domain}/doc/modeling-guidelines/iri-strategy/decisions`

|Data product
|`\https://data.{domain}/dprod/measurements`

|Ontology
|`\https://data.{domain}/ontology/core-equipment`

|Ontology term
|`\https://data.{domain}/ontology/core-equipment#Wire`

|Schema
|`\https://data.{domain}/schema/forecasting`

|Schema element
|`\https://data.{domain}/schema/forecasting#OpertionalLimit`

|Thesaurus
|`\https://data.{domain}/thesaurus/energy-system`

|Thesaurus term
|`\https://data.{domain}/thesaurus/energy-system#usage-point`

|Register
|`\https://id.{domain}/lv-measurements/`

|Register entity
|`\https://id.{domain}/lv-measurements/021`

|===
====
////

== Registers

A register is a logical container of resources which represent entities from the real-world domain. Each register contains one type of entity.

.IRI pattern for a register
[source,subs="attributes"]
....
https://data.{domain}/register/\{namespace}
....

.IRI pattern for a register entity
[source,subs="attributes"]
....
https://id.{domain}/register/\{namespace}/\{reference}
....

[cols="h,2,2",width=70%]
|===
| | Register | Entity

| Resource kind
a| (`data`) data information resource
| (`id`) real-world concept

| Category
2+| `register`

| Namespace
2+| Namespace identifying the register

| Version
2+|_n/a_

| Reference
| _n/a_
| Reference name (local to the register) of the contained entity
|===

== Data product

#TODO#

== Models

.IRI pattern for a model
[source,subs="attributes"]
....
https://data.{domain}/ontology/\{namespace}[/{version}]
....

.IRI pattern for a model element
[source,subs="attributes"]
....
https://id.{domain}/ontology/\{namespace}[/{version}]/\{reference}
....

[cols="h,2,2",width=70%]
|===
| | Model | Element

| Resource kind
a| (`data`) data information resource
| (`id`) real-world concept

| Category
2+| `ontology` \| `thesaurus` \| `schema`

| Namespace
2+| Namespace identifying the model

| Version +
_(optional)_
a| Model version, following the pattern:

`X.Y.Z` +

(where `X, Y, Z` are non-negative integers)
a|_n/a_

| Reference
| _n/a_
| Name (local to the model) of the element
|===

.Are version-less models information resources?
****
#TODO#.
Yes, since it can be represented by information which describes metadata about it and what versions exist of it. Similar to how DCAT manages versions.
****

== Documentation

Documentation intended for reading by humans, not machines. A documentation project can consist of a mere single-page document, but also be comprised of a complex nested structure containing many pages and potentially many layers of organisation.

NOTE: Do not confuse the category _documentation_ with documentation representations as obtained through using `www` IRIs. See also: {fn-doc-iri}

.IRI pattern for a project
[source,subs="attributes"]
....
https://www.{domain}/doc/\{namespace}[/{version}]
....

.IRI pattern for a part
[source,subs="attributes"]
....
https://www.{domain}/doc/\{namespace}[/{version}]/\{reference}
....

[cols="h,2,2",width=70%]
|===
| | Project | Part

| Resource kind
2+| (`www`) documentation information resource

| Category
2+| `doc` footnote:doc-iri[]

| Namespace
2+| Namespace identifying the project

| Version +
_(optional)_
a| Project version, following the pattern:

`X.Y.Z` +

(where `X, Y, Z` are non-negative integers)
a|_n/a_

| Reference
| _n/a_
| Name (local to the project) of the part (e.g. page)
|===

== Data product

Special category which contains data products.

NOTE: This is much like a register, but data product are information resources whereas other registers are not. Therefore, to avoid confusion, and because data products are important, this special category has been introduced.

.IRI pattern for a data product
[source,subs="attributes"]
....
https://data.{domain}/dprod/\{reference}[/{version}]
....

[cols="h,2",width=70%]
|===
| Resource kind
| (`data`) data information resource

| Category
| `dprod`

| Namespace
| _n/a_

| Version +
_(optional)_
a| Data product version, following the pattern:

`X.Y.Z` +

(where `X, Y, Z` are non-negative integers)

| Reference
| Name of the data product
|===




////

== Versioning



== Example

.IRI Strategy
====
Let's consider the IRI for the _IRI Strategy_ document.

.Generic IRI
[source,subs="attributes"]
....
https://www.{domain}/doc/modeling-guide/iri-strategy
....

Note that it is part of the _Modeling Guide_ documentation project, which would act as its container.

To request a specific version of the _Modeling Guide_ one could use the following IRI:

.Versioned IRI
[source,subs="attributes"]
....
https://www.{domain}/doc/modeling-guide/1.1.0/iri-strategy
....

Note that it is not supported to version the _IRI Strategy_ document itself, only the project it is contained in. This is analogous to the inability to version ontology terms.

.IRI to Specific page
[source,subs="attributes"]
....
https://www.{domain}/doc/modeling-guide/iri-strategy/decisions
....

If documentation consists of multiple pages, these can be referenced simply by expanding the path as illustrated in this example.

====

== Models
.IRI pattern for models
[source,subs="attributes"]
....
https://data.{domain}/\{model-type}/\{model}[/\{version}]
....

.IRI pattern for model elements
[source,subs="attributes"]
....
https://data.{domain}/\{model-type}/\{model}[/\{version}]/\{element}
....

[cols="h,1",width=70%]
|===
| Model type
a| Any of:

* `<<x,thesaurus>>`
* `<<x,ont>>`
* `<<x,schema>>`

| Model
| Name of the model

| Version +
_(optional)_
a| Version of the model, following the pattern:

`X.Y.Z` +

(where `X, Y, Z` are non-negative integers)

| Element
| Name (local to the model) of the model element which corresponds to the resource
|===

== Resource kinds

== Versioning

== Example

.LinkML schema of data product _Transitietechnieken_
====
[source,yaml,subs="+attributes"]
....
id: https://data.{domain}/schema/dprod/transitietechnieken <1>
version: 1.0.1 <2>
name: transitietechnieken <3>
prefixes: <4>
  nbnl: https://id.{domain}/taxonomy/energiesysteembeheer/
  cimnl: https://id.{domain}/ont/cim-nl/
classes:
  RegisteredResource:
    class_uri: cim:RegisteredResource
    attributes:
      resource_type:
        slot_uri: cimnl:RegisteredResource.resourceType <5>
        range: ResourceKind
        exact_mappings:
          - nbnl:soortInstallatie <6>
....
<1> The generic IRI of the schema, i.e. not a specific version.
<2> The version of the schema this document represents.
<3> Technical name of the schema. This has local scope, but it is good practice to keep it equal to the model name in the IRI.
<4> Prefixes for easy referring to terms from other models.
<5> Referring to a term from another ontology.
<6> Referring to a term from another thesaurus.
====
////
