= URI Strategy for Models



== URI pattern

NOTE: For data products hierarchical URIs have been considered, which make the tight coupling of some models to its data product more explicit. This quickly gets complicated though.

[source,subs="attributes"]
....
https://\{type}.{domain}/\{namespace}#\{name}
....

URIs are about durable identification, so stating what things exist. Opacity is favored. Relations between models and other things should be part of models. This line of reasoning would lead one towards using flat URIs.

Simple is usually better, and one great example here is how complicated it is to have separate versions for the data product itself and some part. This can be really confusing and difficult to parse. For that reason mostly, I would stick with simple flat URIs.

Then, URIs have no meaning, and the hierarchical relations between things suggested by it merely a convention for humans. Using flat URIs we could come up with another convention to help out humans in relating things to one another. For example, we could have reference names such as `netburen` be unique across the namespaces `data-product`, `ontology`, `schema` and `taxonomy`. That's a very costly and hard to maintain convention though.

Even with flat URIs, conventions will get one a long way. When creating the data product `netburen`, creating an ontology URI for `netburen` could be done immediately. This way, users could simplt replace `data-product` in the URI with `schema` or `ontology` or whatever.

=== Scheme

The entire web moves to HTTPS, so should the Semantic Web. Especially since HTTPS rewrites of HTTP URIs are not equivalent, and since RDF models cannot make statements about URIs themselves to declare them equivalent either, any freshly minted URI should be a HTTPS URI.

=== Type

We will only be looking at the following two types of URIs:

* `data` URIs, which identify models and model elements and their formal, machine-readable representation of resources;
* `www` URIs, which identify web page representations of resources.

[NOTE,caption=scope note]
--
Non-information resourcesfootnote:[Resources whose informational representation is complete are called _information resources_. Effectively their representation is equal to their identity.] -- typically real-world objects -- are identified by a `id` URI which redirects to the various web representations using a 303 redirect. However, this is out of scope for this (version of the) URI strategy, which exclusively deals with models and model elements.
--

=== Namespace

Each model forms the namespace for some element.

CAUTION: Once we start working with registers of instance data as namespaces as well, it is likely the case that slashes will be used there. Out of scope for now.

== Namespaces

=== Models

[cols="1h,1,1"]
|===
| Namespace | Description | Example

| `taxonomy`
| Taxonomy
| `https://data.nbnl.info/taxonomy/nbnl-energiesysteembeheer`

| `ontology`
| Ontology
| `https://data.nbnl.info/ontology/topology`

| `schema`
| Schema
| `https://data.nbnl.info/schema/netburen`

|===

NOTE: Using the `data` URI for data products commits to the promise of providing a machine-readable representation of it.

=== Registers

[cols="1h,1,1"]
|===
| Namespace | Description | Example

| `data-product`
| Data product
| `https://data.nbnl.info/data-product/netburen`

| `document`
| Documentation
| `https://www.nbnl.info/doc/uri-strategy`

|===

NOTE: Because data products are information resources, they make use of the `data` and `www`.

== Decisions and assumptions

[IMPORTANT,caption=decisions]
--
* Hierarchical URIs _should not_ be used.
* Every URI _must_ use HTTPS as its scheme.
* For the identification of models and model definitions:
** `data` URIs _must_ be used.
** `id` URIs _must not_ be used.
* In URIs for model elements, a hash (`#`) character _must_ be used to discern the model element from the model.
* Naming conventions of reference names are out of scope.
--
