= LinkML for UML
Bart Kleijngeld <bartkl@gmail.com>
0.1, March 25, 2024

== Approaches

How to capture the expressiveness of UML in LinkML?

* Snippets
* Templates
* Interpretative enriching
* UML DSL
** Subset of LinkML or full-blown YUMLD language
** OTTR
** YAML-based
* UML Ontology
** Semantics instead of non-committal names

== Snippets

See the screencast video I made March 25th 2025.

== Templates

=== Using Jinja2 extensions

Using custom Jinja2 extensions to correspond with a function, we can parse the contained YAML block as a dictionary which provides the values assigned to its parameters.

==== Attribute per association direction

[source,jinja2]
....
classes:
  Terminal:
    slots:
      {% assoc "cim" %}
        ConductingEquipment:
          range: ConductingEquipment
          required: true
          multivalued: true
          inverse: ConductingEquipment.Terminals
      {% endassoc %}
....

This would expand to:

[source,yaml]
....
classes:
  Terminal:
    slots:
      Terminal.ConductingEquipment:
        slot_uri: cim:Terminal.ConductingEquipment
        domain: Terminal
        range: ConductingEquipment
        required: true
        multivalued: true
        inverse: ConductingEquipment.Terminals
....

==== Relations as subset of slots

[source,jinja2]
....
slots:
    {% relation "hr" %}
    parent:
        class: Person
        primary: true
        required: true
        multivalued: true
    child:
        class: Person
        required: false
        multivalued: false
    {% endrelation %}
....

This expands to:

[source,yaml]
....
slots:
    Person.child:
        slot_uri: people:Person.child
        domain: Person
        range: Person
        required: true
        multivalued: true
        inverse: Person.parent
    Person.parent:
        slot_uri: people:Person.parent
        domain: Person
        range: Person
        required: true
        multivalued: true
        inverse: Person.child
....

===== Issues

# * Both aren't merely local expansions but require references or other definitions in other places. Jinja cannot do that.


== DSL

A dedicated DSL for representing UML on the Semantic Web would not be such a bad idea.

[source,yaml]
....
classes:
  Person:
  Organisation:
associations:
  Employment:
    attributes:
      started:
        type: xsd:date
    participants:
      employee:
        class: Person
        multiplicity: 1
      employer:
        class: Person
        multiplicity: 0..n
....



