= URI Strategy
:domain: nbnl.info

== URI pattern

[source,subs="attributes"]
....
https://\{uri-type}.{domain}/\{container-type}/\{container}{[/\{version}]/\{reference}
....

=== Scheme

The HTTPS scheme is used for all URIs.


=== URI type

The following types of URIs are discerned:

[cols="1h,1,4"]
|===
| `\{uri-type}` | URI type | Identifies

| `id`
| _identity_
| the resource itself, independent of any representation

| `data`
| _definition_
| the formal, machine-readable representation of the resource

| `www`
| _documentation_
| the web page representation of the resource
|===

[NOTE]
--
Unlike many other URI strategies who use identity URIs solely for registers of real-world objects, we also use them for information resources such as ontologies.
--

=== Domain

The domain for every URI is: `nbnl.info`.

=== Container type

Resources are part of a container, and each container is of a certain type.

The following types are recognized:

[cols="2h,5"]
|===
| `\{container-type}` | Description

| `reg`
| Register of individuals

| `dprod`
| Register of data products

| `doc`
| Documentation, for humans

| `ont`
| Ontology or conceptual model

| `schema`
| Logical or technical schema

| `thesaurus`
| Thesaurus, taxonomy, controlled vocabulary or glossary.
|===

NOTE: Unlike other registers which are part of the `reg` register, the `dprod` register is a special case living at the top-level for convenience.

=== Container

Each resource must be part of a container. Containers are of a certain <<_container_type,type>>, and complete the namespace for the resource being identified.

=== Version

This is an optional path component used to version models such as thesauri and ontologies.

NOTE: Versioning of individual resources such as a real-world building or an ontology term is not supported by this URI strategy. This is by design.

=== Reference

Names referencing the resource local to its container.

Conventions regarding the naming of these references depend on the container type. For example, registers may contain numeric references, whereas ontologies should not (#TODO#).

.Identity URIs for an ontology and register
====
The ontology _Core equipment_ describes the term _Wire_. This would yield the following identity URI:

[source,subs="attributes"]
....
https://id.nbnl.info/ont/core-eq/Wire
....

The person _Bart Kleijngeld_ is an individual that is registered with the people register:

[source,subs="attributes"]
....
https://id.nbnl.info/reg/people/bartkl
....
====





== Registers

== Data products

== Documentation

Documentation resources are information resources which are human-readable and on the web.

[source,subs="attributes"]
....
https://\{uri-type}.{domain}/doc/\{container}{[/\{version}]/\{reference}
....

[cols="1h,1"]
|===
| asd | asdasd
| asdasd | asdasd
|===

== Models

Because of the informational nature of <<_information_resources,information resources>>, the _data URI_ which identifies the formal definition also identifies the resource itself, i.e. there is no need for an identity URI.

=== Thesauri

=== Ontologies

=== Schemas

== Types

[cols="2h,5"]
|===
| `\{container-type}` | Description

| `doc`
| Documentation, for humans

| `dprod`
| Register of data products

| `thesaurus`
| Thesaurus, taxonomy, controlled vocabulary or glossary.

| `ont`
| Ontology or conceptual model

| `schema`
| Logical or technical schema
|===


== Versioning

* Models as part of a data product follow the version of the data product, i.e. they do not have an independent version.
* Referring to model elements must be done in a version-less way to ensure durability of the URI.

Models can be versioned, model elements must not be versioned.



== Decisions and assumptions

[IMPORTANT,caption=decisions]
--
* Hierarchical URIs _should not_ be used.
* Every URI _must_ use HTTPS as its scheme.
* For the identification of models and model definitions:
** `data` URIs _must_ be used.
** `id` URIs _must not_ be used.
* In URIs for model elements, a hash (`#`) character _must_ be used to discern the model element from the model.
* Naming conventions of reference names are out of scope.
* As part of their definition, models _must_ describe:
** a versioned URIfootnote:[For example: LinkML would include a version in its schema ID];
** a generic URI;
** a version number according to the SemVer specification.
--

== Terms and definitions

[[def-resource]] resource:: The term _resource_ is used in a general sense for whatever might be identified by a URI. See: <<AWWW>>.

[[def-resource-description]] resource description:: A machine-readable representation of the resource, typically in some serialization of RDF.

[[def-information-resource]] information resource:: A <<def-resource>> which has the property that all of its essential characteristics can be conveyed in a message. See also: <<AWWW>>.
